In [1]:
import numpy as np
import pandas as pd # calling the important libraries

In [2]:
spen1=pd.read_csv("district_spending_expenditure_fy_2018_19.csv") # reading the dataset

In [3]:
spen2=pd.read_csv("district_spending_expenditure_fy_2019_20_lat.csv")

In [4]:
spen1.head() # displaying first 5 rows of spending data of fiscal year 2018_19

,District,Treasury_Code,Treasury,DDO_Code,DDO_Desc,demand,demand_desc,major,major_desc,sub_major,...,plan_nonplan,SOE,SOE_description,TRANSDATE,Voucher,BILLS,GROSS,AGDED,BTDED,NETPAYMENT
0,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2018-04-03,[TRVch#1],1,95660,4000,120,91540
1,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2018-04-03,[TRVch#2],1,267108,43000,12681,211427
2,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,20,OTHER CHARGES,2018-04-17,[TRVch#29],1,10000,0,0,10000
3,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,20,OTHER CHARGES,2018-04-20,[TRVch#32],1,10000,0,0,10000
4,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,5,OFFICE EXPENSES,2018-04-24,[TRVch#52],1,8064,0,0,8064

In [5]:
spen2.head() # displaying first 5 records of fiscal year 2019_20

,District,Treasury_Code,Treasury,DDO_Code,DDO_Desc,demand,demand_desc,major,major_desc,sub_major,...,plan_nonplan,SOE,SOE_description,TRANSDATE,Voucher,BILLS,GROSS,AGDED,BTDED,NETPAYMENT
0,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2019-04-02,[TRVch#1],1,102629,15000,120,87509
1,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2019-04-02,[TRVch#2],1,293928,58800,13874,221254
2,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2019-04-02,[TRVch#3],1,22148,0,9,22139
3,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,3,ADMINISTRATION OF JUSTICE,2014,ADMINISTRATION OF JUSTICE,0,...,N,1,SALARIES,2019-04-08,[TRVch#14],1,6000,0,0,6000
4,BILASPUR,BLP00,BILASPUR,1,CIVIL JUDGE (JR DIVISION) BILASPUR,0,NaN,8009,NaN,1,...,N,47,ADVANCES,2019-04-10,[TRVch#78],1,700000,0,0,700000

In [6]:
spen1=spen1.groupby(['demand','demand_desc', 'major', 'major_desc', 'sub_major',
       'sub_major_desc', 'minor', 'minor_desc', 'sub_minor', 'sub_minor_desc', 'SOE', 'SOE_description'])["NETPAYMENT"].aggregate("mean")
spen1.head() # grouping the dataset by certain columns and finding mean of netpayment

demand  demand_desc   major  major_desc                      sub_major  sub_major_desc           minor  minor_desc            sub_minor  sub_minor_desc                                  SOE  SOE_description
1       VIDHAN SABHA  2011   PARLIAMENT/STATE/U.T.LEGISLATU  2          STATE/U.T. LEGISLATURES  101    LEGISLATIVE ASSEMBLY  1          H.P.VIDHAN SABHA-SPEAKER/DEPUTY SPEAKER [S00N]  1    SALARIES                 2.529804e+05
                                                                                                                                                                                         3    TRAVEL EXPENSES          5.466460e+04
                                                                                                                                                                                         6    MEDICAL REIMBURSEMENT    1.069923e+04
                                                                                                                                                                                         20   OTHER CHARGES            8.491489e+04
                                                                                                                              3          HP VIDHAN SABHA-MEMBERS [S00N]                  1    SALARIES                 1.004075e+07
Name: NETPAYMENT, dtype: float64

In [7]:
spen2=spen2.groupby(['demand','demand_desc', 'major', 'major_desc', 'sub_major',
       'sub_major_desc', 'minor', 'minor_desc', 'sub_minor', 'sub_minor_desc', 'SOE', 'SOE_description'])["NETPAYMENT"].aggregate("mean")
spen2.head()

demand  demand_desc   major  major_desc                         sub_major  sub_major_desc           minor  minor_desc            sub_minor  sub_minor_desc                                  SOE  SOE_description
1       VIDHAN SABHA  2011   PARLIAMENT/STATE/U.T.LEGISLATURES  2          STATE/U.T. LEGISLATURES  101    LEGISLATIVE ASSEMBLY  1          H.P.VIDHAN SABHA-SPEAKER/DEPUTY SPEAKER [S00N]  1    SALARIES                 2.328560e+05
                                                                                                                                                                                            3    TRAVEL EXPENSES          8.930973e+04
                                                                                                                                                                                            6    MEDICAL REIMBURSEMENT    4.687824e+03
                                                                                                                                                                                            20   OTHER CHARGES            8.753778e+04
                                                                                                                                 3          HP VIDHAN SABHA-MEMBERS [S00N]                  1    SALARIES                 6.943185e+06
Name: NETPAYMENT, dtype: float64

In [8]:
spen1.to_excel("spendings_fy_2018_19.xlsx",merge_cells=False) # converting into excel files

In [9]:
spen2.to_excel("spendings_fy_2019_20.xlsx",merge_cells=False)